#ifndef IMAGEENGINE_COMMON_IMGPROC_STRUCT_H_
#define IMAGEENGINE_COMMON_IMGPROC_STRUCT_H_

enum BlurTypes
{
    BLUR_NORMALIZEBOX,
    BLUR_GAUSSIAN,
    BLUR_MEDIAN,
    BLUR_BILATERAL
};

enum ThresholdingTypes
{
    BINARY_THRESHOLD,
    BINARY_THIRESHOLD_INVERT,
    THRESHOLD_TO_ZERO,
    THRESHOLD_TO_ZERO_INVERT
};

#endif